<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>User Report</title>
    <style>
        @page{
            margin: 175px 40px 50px 40px
        }

        .page-break {
            page-break-before: always;
        }

        @font-face {
            font-family: 'Gilroy';
            src: url('{{ resource_path("fonts/Gilroy-Regular.ttf") }}') format('truetype');
            font-weight: normal;
        }

        @font-face {
            font-family: 'Gilroy';
            src: url('{{ resource_path("fonts/Gilroy-Bold.ttf") }}') format('truetype');
            font-weight: bold;
        }
        body {
            font-family: 'Gilroy', sans-serif;
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            /* border: olive solid 1px; */
        }

        header {
            position: fixed;
            top: -125px;
            width: 100%;
            margin-bottom: 10px;
            /* border: red solid 1px; */
        }
        .Header_Text{
            text-align: right;
            font-size: x-small;
        }
        .Header_Text p{
            margin: 0;
            padding: 0;
        }
        header table{
            width: 100%;
            border-collapse: collapse;
        }
        header table td {
            width: 50%;
            margin: 0%;
            padding: 0%;
            vertical-align: top;
        }

        header .Report_Title {
            margin: 0;
            padding: 0;
        }
        .Report_Title h1{
            font-size: small;
            margin: 0;
            padding: 0;
            margin-bottom: 10px;
        }
        .Report_Title p{
            font-size: small;
            margin: 0;
            padding: 0;
        }
        .Report_Title table{
            width: 100%;
            border-collapse: collapse;
            border: 1px solid black;
        }
        .Report_Title table th {
            text-align: left;
            font-weight: bold;
            font-size: x-small;
            padding: 2px 5px;
        }
        .Report_Title table td {
            font-size: xx-small;
            padding: 5px 5px;
        }
        .Report_Title table td,
        .Report_Title table th {
            border: 1px solid black;
        }

        .footer{
            position: fixed;
            width: 100%;
            bottom: -30px;
            border-top: 1px solid;
            padding: 5px 0px 0px 0px;
            border-color: #666666;
        }
        .footer p {
            margin: 0;
            padding: 0;
            font-size: xx-small;
            color: #666666;
        }

        main{
            height: auto;
            margin: 0px 0px 10px 0px;
            padding: 0;
        }
        main p {
            margin: 2px 0px 10px 0px;
            font-size: xx-small;
        }
        main table{
            width: 100%;
            border-collapse: collapse;
        }
        main table td,
        main table th{
            border: 1px solid black;
        }
        main table th{
            text-align: left;
            font-weight: bold;
            font-size: xx-small;
            padding: 2px 5px;
        }
        main table td{
            text-align: left;
            font-size: xx-small;
            padding: 2px 5px;
        }
        main .entries_header {
            text-align: center;
            font-weight: bold;
            font-size: xx-small;
            letter-spacing: 5px;
            border-top: none;
        }

        .basicInfo{
            border-collapse: collapse;
            margin: 0px;
        }

        .basicInfo td,
        .basicInfo th{
            border: 1px solid black;
            font-size: xx-small;
            padding-left: 2px;
        }

        .basicInfo .entries_header{
            font-size: xx-small;
        }


    </style>
</head>
<body>
    <header>
        <table>
            <tr>
                <td>
                    <div class="Header_Logo">
                        <img src="{{ public_path('image/Logo_Report.png') }}" alt="Logo" width="100px">
                    </div>
                </td>
                <td>
                    <div class="Header_Text">
                        <p>Transforming Online Learning </br> Experience</p>
                    </div>
                </td>
            </tr>
        </table>
                <div class="Report_Title">
                    <h1>{{ $name }}</h1>
                    <table>
                        <tr>
                            <th>Generated By:</th>
                            <th>Date Generated:</th>
                            <th>Report Scope</th>
                        </tr>
                        <tr>
                            <td>{{ $genby }}</td>
                            <td>{{ $date }}</td>
                            <td>
                                <!-- {{ $scope ?? 'All Users' }} -->
                                USED FOR: {{ $usedFor }}
                            </td>
                        </tr>
                    </table>
                </div>
    </header>
        @switch($usedFor)
            @case('userList')
                @foreach ($entries as $pageIndex => $chunk)
                    @if ($pageIndex > 0)
                        <div class="page-break"></div>
                    @endif
                    <div>
                        <main>
                            <table>
                                <thead>
                                    <tr>
                                        <th colspan="6" class="entries_header">REPORT ENTRIES</th>
                                    </tr>
                                    <tr>
                                        <th>
                                            No.
                                        </th>
                                        <th>Employee ID</th>
                                        <th>Employee Name</th>
                                        <th>Division</th>
                                        <th>Department</th>
                                        <th>Title</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($chunk as $index => $entry)
                                        <tr>
                                            <td>{{ $pageIndex * 20 + $loop->iteration }}</td>
                                            <td>{{ $entry->employeeID }}</td>
                                            <td style="white-space: nowrap;">{{ $entry->first_name }} {{ $entry->middle_name ? $entry->middle_name : '' }} {{ $entry->last_name }}</td>
                                            <td>{{ $entry->title->department->division->division_name ?? 'N/A' }}</td>
                                            <td>{{ $entry->title->department->department_name ?? 'N/A' }}</td>
                                            <td>{{ $entry->title->title_name ?? 'N/A' }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </main>
                        <div class="footer">
                            <p>{{ $name }} | page {{ $pageIndex + 1 }} of {{ count($entries) }}</p>
                        </div>
                    </div>
                @endforeach
                @break
            <!-- @case('roleDistribution')
                @foreach ($entries as $pageIndex => $chunk)
                    @if ($pageIndex > 0)
                        <div class="page-break"></div>
                    @endif
                    <div>
                        <main>
                            <table>
                                <thead>
                                    <tr>
                                        <th colspan="7" class="entries_header">REPORT ENTRIES</th>
                                    </tr>
                                    <tr>
                                        <th>
                                            No.
                                        </th>
                                        <th>Employee ID</th>
                                        <th>Employee Name</th>
                                        <th>Division</th>
                                        <th>Department</th>
                                        <th>Section</th>
                                        <th>Account Role</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($chunk as $index => $entry)
                                        <tr>
                                            <td>{{ $pageIndex * 10 + $loop->iteration }}</td>
                                            <td>{{ $entry->employeeID }}</td>
                                            <td>{{ $entry->first_name }} {{ $entry->middle_name ? $entry->middle_name : '' }} {{ $entry->last_name }}</td>
                                            <td>{{ $entry->division->division_name ?? 'N/A' }}</td>
                                            <td>{{ $entry->department->department_name ?? 'N/A' }} {{ $entry->title?->title_name ? "({$entry->title->title_name})" : '' }}</td>
                                            <td>{{ $entry->section->section_name ?? 'N/A' }}</td>
                                            <td>{{ $entry->roles->pluck('role_name')->join(', ') ? : 'N/A' }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </main>
                        <div class="footer">
                            <p>{{ $name }} | page {{ $pageIndex + 1 }} of {{ count($entries) }}</p>
                        </div>
                    </div>
                @endforeach
                @break -->
            @case('accountStatus')
                @foreach ($entries as $pageIndex => $chunk)
                    @if ($pageIndex > 0)
                        <div class="page-break"></div>
                    @endif
                    <div>
                        <main>
                            <table>
                                <thead>
                                    <tr>
                                        <th colspan="5" class="entries_header">REPORT ENTRIES</th>
                                    </tr>
                                    <tr>
                                        <th>
                                            No.
                                        </th>
                                        <th>Employee ID</th>
                                        <th>Employee Name</th>
                                        <th>MBLearn Email</th>
                                        <th>Account Role</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($chunk as $index => $entry)
                                        <tr>
                                            <td>{{ $pageIndex * 20 + $loop->iteration }}</td>
                                            <td>{{ $entry->userInfos->employeeID ?? "N/A"}}</td>
                                            <td>{{ $entry->userInfos->first_name ?? "" }} {{ $entry->userInfos->middle_name ?? '' }} {{ $entry->userInfos->last_name ?? ""}}</td>
                                            <td>{{ $entry->MBemail ?? 'N/A' }}</td>
                                            <td>{{ $entry->roles->pluck('role_name')->join(', ') ? : 'N/A' }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </main>
                        <div class="footer">
                            <p>{{ $name }} | page {{ $pageIndex + 1 }} of {{ count($entries) }}</p>
                        </div>
                    </div>
                @endforeach
                @break
            @case('userLogs')
                <table class="basicInfo" style=" width: 100%; border-collapse: collapse;">
                    <thead>
                        <tr>
                            <th colspan="6" class="entries_header">EMPLOYEE BASIC INFORMATION</th>
                        </tr>
                        <tr>
                            <th>EmployeeID:</th>
                            <td>{{ $employee->employeeID ?? "" }}</td>
                            <th>Employee Name:</th>
                            <td>{{ $employee->first_name ?? "" }} {{ $employee->middle_name ? $employee->middle_name : '' }} {{ $employee->last_name ?? "" }}</td>
                            <th>MBLearn Email:</th>
                            <td>{{ $employee->userCredentials->MBemail ?? "" }}</td>
                        </tr>
                    </thead>
                </table>
                @foreach ($entries as $pageIndex => $chunk)
                    @if ($pageIndex > 0)
                        <div class="page-break"></div>
                    @endif
                    <div>
                        <main>
                            <table>
                                <thead>
                                    <tr>
                                        <th colspan="4" class="entries_header">USER LOG ENTRIES</th>
                                    </tr>
                                    <tr>
                                        <th>
                                            No.
                                        </th>
                                        <th>Log Type</th>
                                        <th>Log Descriptions</th>
                                        <th>Log Timestamp</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($chunk as $index => $entry)
                                        <tr>
                                            <td>{{ $pageIndex * 20 + $loop->iteration }}</td>
                                            <td>{{ $entry->log_type ?? 'N/A' }}</td>
                                            <td>{{ $entry->log_description ?? 'N/A' }}</td>
                                            <td>{{ $entry->log_timestamp ?? 'N/A' }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </main>
                        <div class="footer">
                            <p>{{ $name }} | page {{ $pageIndex + 1 }} of {{ count($entries) }}</p>
                        </div>
                    </div>
                @endforeach
                @break
            @case('coursePerformance')
                <table class="basicInfo" style="width: 100%;">
                    <thead>
                        <tr>
                            <th colspan="6" class="entries_header">COURSE BASIC INFORMATION</th>
                        </tr>
                        <tr>
                            <th colspan="1">Course ID:</th>
                            <td colspan="3">{{ $course->courseID }}</td>
                            <th colspan="1">Course Name:</th>
                            <td colspan="3">{{ $course->courseName}}</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>Category</th>
                            <td>{{ $course->categories->category_name ?? "No Category" }}</td>
                            <th>Training Type</th>
                            <td>{{ $course->training_type  }}</td>
                            <th>Career-Level</th>
                            <td>{{ $course->career_level->name }} Level</td>
                        </tr>
                        <tr>
                            <th colspan="1">Author</th>
                            <td colspan="5">{{ $course->author->first_name }} {{ $course->author->middle_name ? $course->author->middle_name : ""  }} {{ $course->author->last_name }} ({{ $course->author->employeeID }})</td>
                        </tr>
                        <tr>
                            <th colspan="1">No. Passed Learners</th>
                            <td colspan="1">{{ $counts['finished'] ?? 0}} Learner/s</td>
                            <th colspan="1">No. of Failed Learner</th>
                            <td colspan="1">{{ $counts['failed'] ?? 0}} Learner/s</td>
                            <th colspan="1">Completion Rate</th>
                            <td>{{ $completionRate }}%</td>
                        </tr>
                    </tbody>
                </table>
                @foreach ($entries as $pageIndex => $chunk)
                    @if ($pageIndex > 0)
                        <div class="page-break"></div>
                    @endif
                    <div>
                        <main>
                            <table>
                                <thead>
                                    <tr>
                                        <th colspan="6" class="entries_header">REPORT ENTRIES</th>
                                    </tr>
                                    <tr>
                                        <th>
                                            No.
                                        </th>
                                        <th col>Employee ID</th>
                                        <th colspan="2">Employee Name</th>
                                        <th>Date of Completion</th>
                                        <th>Remark</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($chunk as $index => $entry)
                                        <tr>
                                            <td>{{ $pageIndex * 20 + $loop->iteration }}</td>
                                            <td>{{ $entry->enrolledUser->employeeID ?? 'N/A' }}</td>
                                            <td colspan="2">{{ $entry->enrolledUser->first_name ?? 'N/A' }} {{ $entry->enrolledUser->middle_name ? $entry->enrolledUser->middle_name : '' }} {{ $entry->enrolledUser->last_name ?? 'N/A' }}</td>
                                            <td >{{ \Carbon\Carbon::parse($entry->updated_at)->format('F d, Y h:i A')}}</td>
                                            <td >{{ $entry->enrollment_status === "finished" ? "Passed" : "Failed"}}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </main>
                        <div class="footer">
                            <p>{{ $name }} | page {{ $pageIndex + 1 }} of {{ count($entries) }}</p>
                        </div>
                    </div>
                @endforeach
                @break
            @case('courseTimeline')
                <table class="basicInfo" style="width: 100%;">
                    <thead>
                        <tr>
                            <th colspan="8" class="entries_header">COURSE BASIC INFORMATION</th>
                        </tr>
                        <tr>
                            <th colspan="1">Course ID:</th>
                            <td colspan="3">{{ $course->courseID }}</td>
                            <th colspan="1">Course Name:</th>
                            <td colspan="3">{{ $course->courseName}}</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>Category</th>
                            <td colspan="3">{{ $course->categories->category_name ?? "No Category"}}</td>
                            <th>Training Type</th>
                            <td>{{ $course->training_type  }}</td>
                            <th>Career-Level</th>
                            <td>{{ $course->career_level->name }} Level</td>
                        </tr>
                        <tr>
                            <th colspan="1">Author</th>
                            <td colspan="7">{{ $course->author->first_name }} {{ $course->author->middle_name ? $course->author->middle_name : ""  }} {{ $course->author->last_name }} ({{ $course->author->employeeID }})</td>
                        </tr>
                        <tr>
                            <th colspan="1">No. of Enrolled Learners</th>
                            <td colspan="1">{{ $statusCount['enrolled_count'] ?? 0}} Learner/s</td>
                            <th colspan="1">No. of Ongoing Learner</th>
                            <td colspan="1">{{ $statusCount['ongoing_count'] ?? 0}} Learner/s</td>
                            <th colspan="1">No. of Past Due Learners</th>
                            <td colspan="1">{{ $statusCount['pastdue_count'] ?? 0}} Learner/s</td>
                            <th colspan="1">No. of Due Soon</th>
                            <td colspan="1">{{ $statusCount['duesoon_count'] ?? 0}} Learner/s</td>
                        </tr>
                    </tbody>
                </table>
                @foreach ($entries as $pageIndex => $chunk)
                    @if ($pageIndex > 0)
                        <div class="page-break"></div>
                    @endif
                    <div>
                        <main>
                            <table>
                                <thead>
                                    <tr>
                                        <th colspan="7" class="entries_header">REPORT ENTRIES</th>
                                    </tr>
                                    <tr>
                                        <th>
                                            No.
                                        </th>
                                        <th col>Employee ID</th>
                                        <th colspan="2">Employee Name</th>
                                        <th>Starting Date</th>
                                        <th>Deadline Date</th>
                                        <th>Remark</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($chunk as $index => $entry)
                                        <tr>
                                            <td>{{ $pageIndex * 10 + $loop->iteration }}</td>
                                            <td>{{ $entry['employeeID']?? 'N/A' }}</td>
                                            <td colspan="2">{{ $entry['user']}}</td>
                                            <td >{{ \Carbon\Carbon::parse($entry['start_date'])->format('M d, Y')}}</td>
                                            <td>{{  \Carbon\Carbon::parse($entry['end_date'])->format('M d, Y')}}
                                            <td >{{ $entry['status']}}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </main>
                        <div class="footer">
                            <p>{{ $name }} | page {{ $pageIndex + 1 }} of {{ count($entries) }}</p>
                        </div>
                    </div>
                @endforeach
                @break
            @case('courseCompletion')
                <table class="basicInfo" style="width: 100%;">
                    <thead>
                        <tr>
                            <th colspan="8" class="entries_header">COURSE BASIC INFORMATION</th>
                        </tr>
                        <tr>
                            <th colspan="1">Course ID:</th>
                            <td colspan="3">{{ $course->courseID }}</td>
                            <th colspan="1">Course Name:</th>
                            <td colspan="3">{{ $course->courseName}}</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>Category</th>
                            <td colspan="3">{{ $course->categories->category_name ?? "No Category"}}</td>
                            <th>Training Type</th>
                            <td>{{ $course->training_type  }}</td>
                            <th>Career-Level</th>
                            <td>{{ $course->career_level->name }} Level</td>
                        </tr>
                        <tr>
                            <th colspan="1">Author</th>
                            <td colspan="7">{{ $course->author->first_name }} {{ $course->author->middle_name ? $course->author->middle_name : ""  }} {{ $course->author->last_name }} ({{ $course->author->employeeID }})</td>
                        </tr>
                        <tr>
                            <th colspan="1">No. of Passed Learners</th>
                            <td colspan="1">{{ $statusCount['passed_count'] ?? 0}} Learner/s</td>
                            <th colspan="1">No. of Failed Learner</th>
                            <td colspan="1">{{ $statusCount['failed_count'] ?? 0}} Learner/s</td>
                            <th colspan="1">No. of On-Time Completers</th>
                            <td colspan="1">{{ $statusCount['on_time'] ?? 0}} Learner/s</td>
                            <th colspan="1">No. of Late Completers</th>
                            <td colspan="1">{{ $statusCount['late'] ?? 0}} Learner/s</td>
                        </tr>
                    </tbody>
                </table>
                @foreach ($entries as $pageIndex => $chunk)
                    @if ($pageIndex > 0)
                        <div class="page-break"></div>
                    @endif
                    <div>
                        <main>
                            <table>
                                <thead>
                                    <tr>
                                        <th colspan="9" class="entries_header">REPORT ENTRIES</th>
                                    </tr>
                                    <tr>
                                        <th>
                                            No.
                                        </th>
                                        <th col>Employee ID</th>
                                        <th colspan="2">Employee Name</th>
                                        <th colspan="2">Date of Completion</th>
                                        <th colspan="2">Deadline Date</th>
                                        <th>Remark</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($chunk as $index => $entry)
                                        <tr>
                                            <td>{{ $pageIndex * 20 + $loop->iteration }}</td>
                                            <td>{{ $entry['employeeID'] ?? 'N/A' }}</td>
                                            <td colspan="2">{{ $entry['user']}}</td>
                                            <td colspan="2" >{{ \Carbon\Carbon::parse($entry['updated_at'])->format('M d, Y')}}</td>
                                            <td colspan="2">{{  \Carbon\Carbon::parse($entry['end_date'])->format('M d, Y')}}
                                            <td >{{ $entry['status']}}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </main>
                        <div class="footer">
                            <p>{{ $name }} | page {{ $pageIndex + 1 }} of {{ count($entries) }}</p>
                        </div>
                    </div>
                @endforeach
                @break
            @case('courseCertification')
                <table class="basicInfo" style="width: 100%;">
                    <thead>
                        <tr>
                            <th colspan="6" class="entries_header">COURSE BASIC INFORMATION</th>
                        </tr>
                        <tr>
                            <th colspan="1">Course ID:</th>
                            <td colspan="1">{{ $course->courseID }}</td>
                            <th colspan="1">Course Name:</th>
                            <td colspan="3">{{ $course->courseName}}</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>Category</th>
                            <td>{{ $course->categories->category_name ?? "No Category"}}</td>
                            <th>Training Type</th>
                            <td>{{ $course->training_type  }}</td>
                            <th>Career-Level</th>
                            <td>{{ $course->career_level->name }} Level</td>
                        </tr>
                        <tr>
                            <th colspan="1">Author</th>
                            <td colspan="5">{{ $course->author->first_name }} {{ $course->author->middle_name ? $course->author->middle_name : ""  }} {{ $course->author->last_name }} ({{ $course->author->employeeID }})</td>
                        </tr>
                    </tbody>
                </table>
                <main>
                    @foreach ($entries as $index => $enty)
                        @if ($index % 20 == 0)
                            @if ($index > 0)
                                <div class="page-break"></div>
                            @endif
                        <table>
                            <thead>
                                <tr>
                                    <th colspan="5" class="entries_header">REPORT ENTRIES</th>
                                </tr>
                                <tr>
                                    <th>No.</th>
                                    <th>Employee ID</th>
                                    <th colspan="2">Employee Name</th>
                                    <th>Date of Completion</th>
                                </tr>
                            </thead>
                            <tbody>
                    @endif
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $enty->enrolledUser->employeeID ?? 'N/A' }}</td>
                            <td colspan="2">
                                {{ $enty->enrolledUser->first_name ?? '' }}
                                {{ $enty->enrolledUser->middle_name ?? '' }}
                                {{ $enty->enrolledUser->last_name ?? '' }}
                            </td>
                            <td>{{ \Carbon\Carbon::parse($enty->updated_at)->format('M d, Y') }}</td>
                        </tr>

                        @if (($index + 1) % 20 == 0 || $index + 1 == $entries->count())
                                </tbody>
                            </table>
                        @endif
                    @endforeach
                </main>
            @break
            @case('assessmentresults')
                <table class="basicInfo" style="width: 100%;">
                    <thead>
                        <tr>
                            <th colspan="8" class="entries_header">TEST BASIC INFORMATION</th>
                        </tr>
                        <tr>
                            <th colspan="1">Test Name:</th>
                            <td colspan="3">{{ $test->TestName }}</td>
                            <th colspan="1">Course Name:</th>
                            <td colspan="3">{{ $course->courseName}}</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>Category</th>
                            <td colspan="3">{{ $course->categories->category_name ?? "No Category"}}</td>
                            <th>Training Type</th>
                            <td>{{ $course->training_type  }}</td>
                            <th>Career-Level</th>
                            <td>{{ $course->career_level->name }} Level</td>
                        </tr>
                        <tr>
                            <th colspan="1">Author</th>
                            <td colspan="7">{{ $course->author->first_name }} {{ $course->author->middle_name ? $course->author->middle_name : ""  }} {{ $course->author->last_name }} ({{ $course->author->employeeID }})</td>
                        </tr>
                        <tr>
                            <th colspan="1">Passed Learners</th>
                            <td colspan="1">{{ $stats['passed'] ?? 0}} Learner/s</td>
                            <th colspan="1">Failed Learners</th>
                            <td colspan="1">{{ $stats['failed'] ?? 0}} Learner/s</td>
                            <th colspan="1">Total Assessment Takers</th>
                            <td colspan="1">{{ $stats['total'] ?? 0}} Learner/s</td>
                            <th colspan="1">Average Attempt Taken</th>
                            <td colspan="1">{{ $stats['average'] ?? 0}} Attempts/s</td>
                        </tr>
                    </tbody>
                </table>
                @foreach ($entries as $pageIndex => $chunk)
                    @if ($pageIndex > 0)
                        <div class="page-break"></div>
                    @endif
                    <div>
                        <main>
                            <table>
                                <thead>
                                    <tr>
                                        <th colspan="6" class="entries_header">REPORT ENTRIES</th>
                                    </tr>
                                    <tr>
                                        <th>
                                            No.
                                        </th>
                                        <th col>Employee ID</th>
                                        <th colspan="2">Employee Name</th>
                                        <th>Best Score Attempt</th>
                                        <th>Remark</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($chunk as $index => $entry)
                                        <tr>
                                            <td>{{ $pageIndex * 20 + $loop->iteration }}</td>
                                            <td>{{ $entry['employeeID'] ?? 'N/A' }}</td>
                                            <td colspan="2">{{ $entry['user']}}</td>
                                            <td >{{ $entry['bestScore']}}</td>
                                            <td >{{ $entry['status']}}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </main>
                        <div class="footer">
                            <p>{{ $name }} | page {{ $pageIndex + 1 }} of {{ count($entries) }}</p>
                        </div>
                    </div>
                @endforeach
            @break
                @default
                <main>
                    <p>No entries found for this report.</p>
                </main>
                <div class="footer">
                    <p>{{ $name }} | page 1 of 1</p>
                </div>
                @break
        @endswitch


</body>
</html>
